server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shoeshop"
    username: shoeshop
    password: shoeshop123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    prefix: classpath:/templates/webapp/
    # Đặt đường dẫn cho thư mục templates của bạn
    suffix: .html                         # Phần mở rộng của các tệp mẫu
    mode: HTML                            # Định dạng HTML
    encoding: UTF-8                       # Mã hóa ký tự
    cache: false                          # Vô hiệu hóa bộ nhớ đệm khi phát triển
  mail:
    host: smtp.gmail.com
    port: 587
    username: nd2004lk13@gmail.com
    password: swwa kcsa bbma gvlc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
